os: linux
sudo: required
language: python
python:
  - "3.6"

services:
  - docker

env:
  COMPOSE_PROJECT_NAME=psychrowebcam
  LABEL=x64

  LOGGING_LEVEL=INFO
  LOGGING_LEVEL_CELERY_WORKER=INFO
  LOGGING_LEVEL_CELERY_BEAT=INFO
  GUNICORN_NUM_WORKERS=4
  CELERY_NUM_WORKERS=10
  PORT=8000
  CUSTOM_PATH=./custom
  REDIS_PWD=ultrastrongpassword

script:
  - docker-compose build psychrocam
#  - docker-compose up
