version: '3'

services:
  psychrocam:
    image: azogue/psychrocam:latest
    build: .
    container_name: psychrocam
    restart: always
    environment:
      - APP_SETTINGS=${APP_SETTINGS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - RUNNING_IN_DOCKER=${RUNNING_IN_DOCKER}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PWD=${REDIS_PWD}
    ports:
      - "${PORT}:8000"
    volumes:
      - ${CUSTOM_PATH}:/psychrocam/psychrocam/static/custom
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass ${REDIS_PWD}
    hostname: redis
    container_name: redis
    restart: always
    networks:
      - redis-net

networks:
  redis-net:
