version: '3'

services:
  psychrocam:
    image: "azogue/psychrocam:${LABEL}"
    build:
      context: .
      args:
        label_arch: '${LABEL}'
    container_name: psychrocam
    restart: always
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - REDIS_URL=redis://:${REDIS_PWD}@redis:6379/0
      - REDIS_PWD=${REDIS_PWD}
    ports:
      - "${PORT}:8000"
    volumes:
      - ${CUSTOM_PATH}:/psychrocam/psychrocam/static/custom
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass ${REDIS_PWD}
    hostname: redis
    container_name: redis
    restart: always
    networks:
      - redis-net

networks:
  redis-net:
